<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <title>Добавяне на книга</title>
            <link rel="stylesheet" type="text/css" href="forms/bookform/view.css" media="all">
                <script type="text/javascript" src="forms/bookform/view.js"></script>

                </head>
                <body id="main_body" >

                    <img id="top" src="forms/bookform/top.png" alt="">
                        <div id="form_container">

                            <h1><a>Добавяне на книга</a></h1>
                            <form id="form_96448" class="appnitro"  method="post" action="">
                                <div class="form_description">
                                    <h2>Добавяне на книга</h2>
                                    <p></p>
                                </div>						
                                <ul >

                                    <li id="li_3" >
                                        <label class="description" for="element_3">Автор </label>
                                        <div>
                                            <select class="element select medium" id="element_3" name="element_3"> 
                                                <option value="" selected="selected"></option>
                                             <?php
                                             $authors = $user->getAllUsers();
                                                for( $i = 0; $i<count($authors);$i++){
                                                    echo "<option value=\"".$authors[$i]['id']."\" >".$authors[$i]['firstname']." ".$authors[$i]['lastname']."</option>";
                                                }
                                               ?>
                                            </select>
                                        </div> 
                                    </li>		<li id="li_1" >
                                        <label class="description" for="element_1">Заглавие </label>
                                        <div>
                                            <input id="element_1" name="element_1" class="element text medium" type="text" maxlength="255" value=""/> 
                                        </div> 
                                    </li>		<li id="li_2" >
                                        <label class="description" for="element_2">Кратко описание </label>
                                        <div>
                                            <textarea id="element_2" name="element_2" class="element textarea medium"></textarea> 
                                        </div> 
                                    </li>

                                    <li class="buttons">
                                        <input type="hidden" name="form_id" value="96448" />

                                        <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
                                    </li>
                                </ul>
                            </form>	
                            <div id="footer">
                                Generated by <a href="http://www.phpform.org">pForm</a>
                            </div>
                        </div>
                        <img id="bottom" src="forms/bookform/bottom.png" alt="">
                            </body>
                            </html>