<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Добавяне на потребител</title>
<link rel="stylesheet" type="text/css" href="forms/userform/view.css" media="all">
<script type="text/javascript" src="forms/userform/view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="forms/userform/top.png" alt="">
	<div id="form_container">
	
		<h1><a>Добавяне на потребител</a></h1>
		<form id="form_96448" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Добавяне на потребител</h2>
			<p></p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Име </label>
		<span>
			<input id="element_1_1" name= "element_1_1" class="element text" maxlength="255" size="8" value=""/>
			<label>First</label>
		</span>
		<span>
			<input id="element_1_2" name= "element_1_2" class="element text" maxlength="255" size="14" value=""/>
			<label>Last</label>
		</span> 
		</li>		<li id="li_4" >
		<label class="description" for="element_4">Никнейм </label>
		<div>
			<input id="element_4" name="element_4" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Email </label>
		<div>
			<input id="element_2" name="element_2" class="element text medium" type="text" maxlength="255" value=""/> 
		</div> 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Парола </label>
		<div>
                    <input id="element_3" name="element_3" class="element text medium" type="password" maxlength="255" value=""/> 
                    <input id="view_pass" type="button" value="Виж паролата" onclick="sitch()">
		</div> 
		</li>		<li id="li_5" >
		<label class="description" for="element_5">Автор? </label>
		<span>
			<input id="element_5_1" name="element_5_1" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_5_1">Регистрация като автор</label>

		</span> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="96448" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
                                <input id="saveForm" class="button_text" type="reset" name="buti" value="Reset" style="float:right;"/>
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="forms/userform/bottom.png" alt="">
	</body>
</html>
<script>

function sitch(){
 var c=  document.getElementById("view_pass").value;
    if(c=="Виж паролата"){
        document.getElementById("view_pass").value="Скрий паролата";
         document.getElementById("element_3").type="text";
        
    }else{
          document.getElementById("view_pass").value="Виж паролата";
          document.getElementById("element_3").type="password";
    }
}</script>